class Settings:
    FPS = 60
    SCREEN_WIDTH, SCREEN_HEIGHT = 1200, 800
    BG_COLOR = (0, 0, 0)
    PLAYER_SPEED = 450
    BASIC_ENEMY_SPEED = 5
    PROJECTILE_SPEED = 600
    PROJECTILE_WIDTH = 5
    PROJECTILE_HEIGHT = 20
    BTN_PADDING = 5
    SMALL_FONT_SIZE = 35
