from enum import IntEnum


class Settings(IntEnum):
    FPS = 60
    SCREEN_WIDTH = 1200
    SCREEN_HEIGHT = 800
    GAME_WINDOW_WIDTH = 900
    GAME_WINDOW_HEIGHT = 800
    SIDE_MENU_WIDTH = 300
    SIDE_MENU_HEIGHT = 800
    ACTOR_WIDTH = 50
    ACTOR_HEIGHT = 50
    OBSTACLE_WIDTH = 70
    OBSTACLE_HEIGHT = 50
    PLAYER_SPEED = 450
    BASIC_ENEMY_SPEED = 200
    PROJECTILE_SPEED = 600
    PROJECTILE_WIDTH = 5
    PROJECTILE_HEIGHT = 20
    BTN_WIDTH = 300
    BTN_HEIGHT = 45
    BTN_PADDING = 5
    SMALL_FONT_SIZE = 35
