from enum import IntEnum


class Settings(IntEnum):
    FPS = 60
    SCREEN_WIDTH = 1200
    SCREEN_HEIGHT = 800
    GAME_WINDOW_WIDTH = 900
    GAME_WINDOW_HEIGHT = 800
    GAME_WINDOW_PADDING = 15
    SIDE_MENU_WIDTH = 300
    SIDE_MENU_HEIGHT = 800
    PLAYER_WIDTH = 40
    PLAYER_HEIGHT = 30
    PLAYER_SPEED = 450
    BASIC_ENEMY_WIDTH = 45
    BASIC_ENEMY_HEIGHT = 35
    BASIC_ENEMY_SPEED = 200
    OBSTACLE_WIDTH = 70
    OBSTACLE_HEIGHT = 50
    PROJECTILE_SPEED_PLAYER = 700
    PROJECTILE_SPEED_ENEMY = 400
    PROJECTILE_WIDTH = 5
    PROJECTILE_HEIGHT = 15
    BTN_WIDTH = 300
    BTN_HEIGHT = 45
    BTN_PADDING = 5
    SMALL_FONT_SIZE = 35
    ENEMY_COLUMN_COUNT = 10
    OBSTACLE_HIT_COUNT = 7

